### ISSUE TITLE
End of free trial.

### ISSUE THREAD

**Issue by cwbeck** [scale8/tag-manager#69]
- Make sure if negative, "your trial ended 'n' days ago".
- If no days left <=0, ~~then redirect to settings of org and~~ show message prompting for update of plan to paid.
  - Only do this at the account level. So if moving to tag manager and account is not on a plan after free trail, prompt.

**Comment by a-barzanti** [comment]
We decided to avoid redirect and give more emphasis to the existing message ( red? )
